site_name: Project Docs
theme:
  name: material
nav:
  - Home: index.md
  - Architecture: architecture.md
  - Overview: architecture_auto.md

plugins:
  - search

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
