# Debug config for quick SAE runs (small, deterministic-ish)

encoders:
  - resnet50imagenet

# Use a single CSV with a split column for simplicity
single_csv_path: /path/to/debug_tiles.csv  # columns: tile, split (train/val), + optional labels (ignored)
data_dir: /path/to/dataset_root
tile_subdir: tiles
split_col_name: split

# Training (small)
epochs: 2            # debug a 1-2 epoch loop
batch_size: 8
num_workers: 0       # avoid multiprocessing in debug
image_size: 128
precision: 32
deterministic: true

# SAE hyperparameters (smaller hidden for speed)
sae:
  d_hidden: 512
  k: 32
  allow_negative_topk: false
  learning_rate: 1.0e-3
  weight_decay: 1.0e-2

# Minimal augs
hflip: false
rot90s: false
affine: false
color_jitter: false

