project: CD4, CD8A unimodel bins lr
name: compare cms gene performance
method: grid
metric:
  name: valid_loss
  goal: minimize

parameters:
  debug:
    value: false
  log_to_wandb:
    value: true
  # fixed
  epochs:
    value: 40
  dataset:
    value: CRC_N19
  encoder_type:
    value: unimodel
  batch_size:
    value: 64
  genes:
    value: [CD4, CD8A]#[CD3D,CCL5,SIRPG,CD40LG,CD4,TRAT1,CD69,RORA,CD8A,NKG7,GZMA,GZMB,GZMK,PRF1]
  error_metric_name:
    value: MSE
  middle_layer_features:
    value: 200
  num_workers:
    value: 2
  loss_fn_switch:
    value: MSE
  gene_data_filename:
    values: [gene_data_log1p.csv, gene_data_log1p.csv] #gene_data_log1p.csv, gene_data_ranknorm.csv
  image_size:
    value: 224
  generate_scatters:
    value: true
  use_early_stopping:
    value: true
  use_leaky_relu:
    value: false
  one_linear_out_layer:
    value: false
  # hyperparams
  global_fix_learning_rate:
    values: [0.1, 0.01, 0.001]
  freeze_encoder:
    value: true
  bins:
    values: [1,3,5,7,10]