# LDS weight generation config (no training)
# Use with: python -m script.data_processing.lds --config sweeps/configs/lds/lds_config.yaml

parameters:
  # Dataset selection (uses script/configs/dataset_config.py)
  dataset:
    value: CRC_N19            # <-- change to your dataset key if different
  gene_data_filename:
    value: gene_data_ranknorm.csv  # <-- change to the label CSV used for training
  meta_data_dir:
    value: /meta_data/        # <-- change to 'metadata' if your dataset uses that

  # Genes to generate weights for (required)
  genes:
    values: [RUBCNL]          # <-- replace with your gene list (e.g., [TNNT1, AQP5, RAMP1, ...])

  # LDS sweep config (optional; these defaults are reasonable)
  kernel_type:
    value: gaussian           # one of: gaussian, silverman, triang, laplace
  bin_space:
    values: [20, 30, 40, 50, 100]
  ks_space:
    values: [7, 9, 11]
  sigma_space:
    values: [0.8, 1.0, 1.2, 1.5, 2.0]

  # Outputs
  lds_out_csv:
    value: best_smoothing.csv
  lds_out_plots_dir:
    value: lds_plots

  # Optional: override default splits from dataset_config
  # Provide BOTH or neither (only train is used for LDS, but resolver requires both)
  # train_samples: ["TENX92","TENX91","TENX90"]
  # val_samples:   ["TENX29","ZEN43"]

  # Debug mode: limit rows for quick iteration
  debug:
    value: false

