%%{init:{
  "securityLevel":"loose",
  "flowchart":{"htmlLabels":true,"nodeSpacing":36,"rankSpacing":72,"useMaxWidth":true},
  "themeVariables":{"fontSize":"19px"}
}}%%
flowchart TB
subgraph Outputs [Outputs]
  direction TB
end

